name: Run tests
 
on: [push]

jobs:
  tests:
    name: Run tests

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: appointment_api_test
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pgsql, pdo_pgsql, bcmath, soap, intl, gd, exif, iconv
        coverage: none

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Prepare Laravel Application
      run: |
        cp .env.example .env
        php artisan key:generate      

    - name: Run Migrations & Seeders
      run: php artisan migrate:fresh --seed
      env:
        DB_CONNECTION: pgsql
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_DATABASE: appointment_api_test
        DB_USERNAME: runner
        DB_PASSWORD: password

    - name: Run Tests
      env:
        DB_CONNECTION: pgsql
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_DATABASE: appointment_api_test
        DB_USERNAME: runner
        DB_PASSWORD: password
        APP_KEY: ${{ secrets.APP_KEY }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
      run: php artisan test 